export const TECHNOLOGY_CATEGORY_LABELS: Record<string, string> = {
  ai: "AI & ML",
  apis: "APIs",
  auth: "Auth & Collaboration",
  backend: "Backend",
  bioinformatics: "Bioinformatics",
  cicd: "CI/CD",
  cli: "CLI",
  cloud: "Cloud",
  codeQuality: "Code Quality",
  computing: "Computing",
  containerization: "Containerization",
  core: "Core",
  dataFormats: "Data Formats",
  dataProcessing: "Data Processing",
  dataStructures: "Data Structures",
  deployment: "Deployment",
  development: "Development Tools",
  distributedComputing: "Distributed Computing",
  distribution: "Distribution",
  documentation: "Documentation",
  framework: "Frameworks",
  frameworks: "Frameworks",
  frontend: "Frontend",
  geospatial: "Geospatial",
  hpcTools: "HPC Tools",
  infrastructure: "Infrastructure",
  landingPage: "Landing Page",
  machineLearning: "Machine Learning",
  modeling: "Modeling",
  naturalLanguageToolkit: "Natural Language Toolkit",
  optimization: "Optimization",
  packageManagement: "Package Management",
  profiling: "Profiling",
  programming: "Programming",
  science: "Scientific Computing",
  scienceSpecific: "Science Specific",
  simulation: "Simulation",
  testing: "Testing",
  vectorDatabases: "Vector Databases",
  visualization: "Visualization",
};

export function getTechnologyCategoryLabel(categoryId: string): string {
  return TECHNOLOGY_CATEGORY_LABELS[categoryId] ?? categoryId;
}
