name: Build the site

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build_impl@PRBuild # BugBug main
