name: Build and Deploy to GitHub Pages

on:
  pull_request:
    branches: ['main']

  push:
    branches: ['main']

  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment per event and branch
concurrency:
  group: 'pages-${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v4
